services:
  model:
    build:
      context: .
      dockerfile: Dockerfile.model
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "8080:80"

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    environment:
      - MODEL_ENDPOINT=http://model:80
    depends_on:
      model:
        condition: service_healthy
    ports:
      - "5001:5000" 