version: '3.8'

services:
  model:
    build:
      context: .
      dockerfile: Dockerfile.model
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "8080:80"
    networks:
      - pynucleus-network

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    environment:
      - MODEL_ENDPOINT=http://model:80
      - PYTHONPATH=/app/src
      - PYNUCLEUS_API_KEY=docker
    depends_on:
      model:
        condition: service_healthy
    ports:
      - "5001:5000"
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
    networks:
      - pynucleus-network

  # Main application service
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - PYTHONPATH=/app/src
      - PYTHONUNBUFFERED=1
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
      - ../configs:/app/configs
    ports:
      - "8888:8888"  # For Jupyter if needed
    networks:
      - pynucleus-network

networks:
  pynucleus-network:
    driver: bridge 