# === Consolidated Calibration Module ===
# --- From train_confidence.py ---
# ... existing code ...
# --- From validation_manager.py ---
# ... existing code ...
# --- From confidence_calibration.py ---
# ... existing code ...
# --- From semantic_validation.py ---
# ... existing code ...
# --- From golden_eval.py ---
# ... existing code ...
# --- From __init__.py (if any relevant logic) ---
# ... existing code ... 