# === Consolidated RAG Module ===
# --- From engine.py ---
# ... existing code ...
# --- From answer_processing.py ---
# ... existing code ...
# --- From collector.py ---
# ... existing code ...
# --- From document_processor.py ---
# ... existing code ...
# --- From vector_store.py ---
# ... existing code ...
# --- From rag_core.py ---
# ... existing code ...
# --- From vector_store_remote.py ---
# ... existing code ...
# --- From wiki_scraper.py ---
# ... existing code ...
# --- From embedding_monitor.py ---
# ... existing code ...
# --- From __init__.py (if any relevant logic) ---
# ... existing code ... 