name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,test]
        
    - name: Lint with ruff
      run: |
        ruff check --output-format=github .
        
    - name: Type check with mypy
      run: |
        mypy src
        
    - name: Run tests with pytest
      run: |
        pytest -q 
        
    - name: Test DSPy Compilation
      run: |
        # Test DSPy compilation in CI mode (creates artifact but doesn't commit)
        python run_pipeline.py dspy-compile --ci
        
    - name: Flask smoke test
      run: |
        export PYNUCLEUS_API_KEY=dummy
        FLASK_APP=pynucleus.api.app flask routes